Payments Flow Mapping
The Payments Flow Mapping project aims to enhance the visibility and control of payment processes by providing comprehensive tracking and monitoring capabilities across all payment channels. This initiative was developed in response to isolated payment issues that revealed limited visibility into where and how breakdowns occur within the end-to-end payments process. The project utilizes a systematic approach to map current-state processes, identify gaps, and establish robust monitoring frameworks that enable proactive identification of payment bottlenecks and failures.
Though comprehensive in scope, the project will be implemented through a phased approach starting with research and discovery. We opted for this methodical strategy because it allows us to engage with every group involved in the payment lifecycle, document current-state processes, and build a solid foundation for future enhancements. The initiative intends to eventually establish streamlined workflows and scalable infrastructure that can accommodate growing payment volumes while maintaining operational excellence.
Recent Accomplishments:

Held two successful cross-functional workshops with key stakeholders across the broader payments organization to align on objectives and begin building a shared understanding of the full payments flow.
Conducted deep-dive sessions with core applications to map current-state processes, identify pain points, and understand system-level tracking capabilities across SPS, CPA, DPH, PINNACLE, WEB, MBL, and PPO.
Began compiling findings and themes across systems and teams to inform the initial set of comprehensive recommendations for improved process visibility.
Started drafting a high-level payments flow diagram to illustrate how transactions move throughout the bank, highlighting visibility gaps and identifying key opportunities for improved monitoring and traceability.
